
language: python
python:
# - "3.3"
# - "3.4"
 - "3.5"
 - "nightly" # currently points to 3.6-dev

install:
# The `-e` and `develop` hack is due to weirdness in namespace packages
 - "pip install git+https://github.com/ActivityWatch/aw-core.git#egg=aw-core"
 - "python3 setup.py install"

script:
 - "python3 -c 'import aw_server'"
